; ============================================================================
; raycast.asm — VZ-DOOM Milestone 2: the raycaster
; ============================================================================
; True 3D: 32 rays cast through a 16x16 grid map, perspective wall slices,
; fisheye-corrected, two-tone wall faces (front=red, side=blue), rendered
; in Mode 1 (128x64, 2bpp). View rotates slowly (1 angle unit per 4 frames).
;
; Engine numbers:
;   positions   8.8 fixed point (high byte = map cell)
;   angles      256 units per revolution
;   ray march   1/8 cell per step (step vectors pre-scaled in tables)
;   distance    step count (1/8-cell units), fisheye-corrected via
;               (dist * FISH[col]) >> 8, then HLUT -> even wall height 2..62
;
; Tables (tables.inc, generated by tools/gen_tables.py):
;   MAP     256B  16x16 cells, idx = (ycell<<4)|xcell, nonzero = wall
;   STEPXL/STEPXH/STEPYL/STEPYH  4x256B consecutive pages, indexed by angle
;   FISH    32B   256*cos(column offset from view centre), clamped 255
;   HLUT    256B  corrected distance -> wall height
;
; Register plan (ray march inner loop, ~107 T-states/step):
;   primary: HL=posX  DE=stepX  B=HIGH MAP  C=cell index scratch
;   alt:     HL'=posY DE'=stepY B'=distance
;
; Verified against tools/gen_tables.py reference frame in a Z80 simulator
; (tools/z80sim.py) — VRAM output is byte-exact.
;
; Build:  ..\build.ps1 src\raycast.asm RAYCAST
; Exit:   RESET button
; ============================================================================

        DEVICE  NOSLOT64K

VRAM    EQU     $7000
LATCH   EQU     $6800

        ORG     $7AE9

START:
        DI                      ; ROM VBlank IRQ would rewrite the latch
        LD      SP, $8FFE

        LD      A, %00001000    ; Mode 1, CSS=0
        LD      (LATCH), A

        LD      A, 64           ; facing +Y
        LD      (PANGV), A
        XOR     A
        LD      (SPIN), A
        LD      HL, $0780       ; player (7.5, 2.5)
        LD      (PXV), HL
        LD      HL, $0280
        LD      (PYV), HL

; ----------------------------------------------------------------------------
MAIN:
        XOR     A
        LD      (COLV), A

COL:
        ; ---- ray angle = PANG + 31 - 2*col  (col 0 = leftmost) ----
        LD      A, (COLV)
        ADD     A, A
        LD      E, A
        LD      A, (PANGV)
        ADD     A, 31
        SUB     E               ; A = angle (byte wrap intended)

        ; ---- step vectors from consecutive table pages ----
        LD      L, A
        LD      H, HIGH STEPXL
        LD      E, (HL)
        INC     H               ; -> STEPXH
        LD      D, (HL)         ; DE = stepX (signed 16)
        INC     H               ; -> STEPYL
        LD      A, (HL)
        INC     H               ; -> STEPYH
        LD      H, (HL)
        LD      L, A            ; HL = stepY
        PUSH    HL
        EXX
        POP     DE              ; DE' = stepY
        LD      HL, (PYV)       ; HL' = posY
        LD      B, 0            ; B'  = distance
        EXX
        LD      HL, (PXV)       ; HL  = posX
        LD      B, HIGH MAP     ; BC  = map cell pointer

        ; ---- march the ray until a wall cell ----
RSTEP:
        ADD     HL, DE          ; posX += stepX
        LD      A, H
        AND     $0F
        LD      C, A            ; C = xcell
        EXX
        ADD     HL, DE          ; posY += stepY
        LD      A, H
        INC     B               ; distance++
        EXX
        AND     $0F
        RRCA
        RRCA
        RRCA
        RRCA                    ; A = ycell << 4
        OR      C
        LD      C, A            ; BC -> MAP[(ycell<<4)|xcell]
        LD      A, (BC)
        OR      A
        JR      Z, RSTEP

        ; ---- face: did the final step cross an X cell boundary? ----
        LD      A, H
        AND     $0F
        LD      C, A            ; C = xcell at hit
        OR      A               ; clear carry
        SBC     HL, DE          ; posX before the final step
        LD      A, H
        AND     $0F
        CP      C
        LD      A, $FF          ; same xcell -> Y-boundary hit -> front: red
        JR      Z, .face
        LD      A, $AA          ; X crossing -> side face: blue
.face:  LD      (WALLB), A

        ; ---- fisheye-corrected distance: (dist * FISH[col]) >> 8 ----
        EXX
        LD      A, B            ; A = distance in 1/8-cell steps
        EXX
        LD      D, A
        LD      A, (COLV)
        LD      L, A
        LD      H, HIGH FISH
        LD      E, (HL)         ; E = fisheye cos factor
        LD      A, D            ; A = distance
        LD      D, 0            ; DE = factor
        LD      HL, 0
        LD      B, 8
.mul:   ADD     HL, HL
        ADD     A, A
        JR      NC, .ms
        ADD     HL, DE
.ms:    DJNZ    .mul            ; HL = dist * factor; H = >>8

        ; ---- wall height and ceiling size ----
        LD      L, H
        LD      H, HIGH HLUT
        LD      A, (HL)         ; A = wall height (even, 2..62)
        LD      (WALLN), A
        LD      B, A
        LD      A, 64
        SUB     B
        SRL     A
        LD      (CEILN), A      ; ceiling rows = floor rows

        ; ---- render the column (same body as wavedemo) ----
        LD      A, (COLV)
        LD      L, A
        LD      H, HIGH VRAM
        LD      DE, 32

        LD      A, (CEILN)
        OR      A
        JR      Z, .wall
        LD      B, A
        XOR     A               ; ceiling: $00 green
.cl:    LD      (HL), A
        ADD     HL, DE
        DJNZ    .cl

.wall:  LD      A, (WALLN)
        LD      B, A
        LD      A, (WALLB)
.wl:    LD      (HL), A
        ADD     HL, DE
        DJNZ    .wl

        LD      A, (CEILN)
        OR      A
        JR      Z, .cnext
        LD      B, A
        LD      A, $55          ; floor: yellow
.fl:    LD      (HL), A
        ADD     HL, DE
        DJNZ    .fl

.cnext: LD      A, (COLV)
        INC     A
        LD      (COLV), A
        CP      32
        JP      NZ, COL

        ; ---- frame complete: rotate view every 4th frame ----
        LD      A, (SPIN)
        INC     A
        LD      (SPIN), A
        AND     3
        JP      NZ, MAIN
        LD      A, (PANGV)
        INC     A
        LD      (PANGV), A
        JP      MAIN

; ----------------------------------------------------------------------------
PANGV:  DB      0               ; view angle
SPIN:   DB      0               ; frame counter for rotation rate
COLV:   DB      0               ; current column
CEILN:  DB      0               ; ceiling/floor row count
WALLN:  DB      0               ; wall row count
WALLB:  DB      0               ; wall byte (face colour)
PXV:    DW      0               ; player X (8.8)
PYV:    DW      0               ; player Y (8.8)

        INCLUDE "tables.inc"

CODEEND:

        SAVEBIN "build/raycast.bin", START, CODEEND - START
